### ISSUE TITLE
Treatment of default()

### ISSUE THREAD

**Issue by brabeji** [hjkcai/typesafe-joi#7]
Hello @hjkcai !

I'm using `Joi.object(...).default({})` to autovivify my form structure prior validation. There is a slight problem with typings, where the resulting value type is still possibly undefined. I think it may be a valid assumption that default value is at least extended by any valid value, so we can make resulting type "required":

```
default (value?: any, description?: string): RequiredSchemaType<Schema, ExcludeUndefined<Value>>
```

Moreover, I can't make a schema both `required()` and `default()` because of https://github.com/hapijs/joi/issues/811 . What do you think?

I ❤️ `typesafe-joi` so much, thank you!

**Comment by hjkcai** [comment]
Hey brabeji. I really appreciate that you love typesafe-joi 😀😀😀 Thanks!

I will work on it later. PR is welcomed!

But I still have some questions:

1. What if the type of default value is different with the schema type? e.g. `Joi.number().default('oops')`. If this results `number | string`, the definition of `value` parameter will be complicated.
2. Simply using `RequiredSchema` may cause the schema to become optional if user call `.optional()` on it. I think we need another schema type. Maybe `DefaultSchmea`?

**Comment by brabeji** [comment]
Hello, @hjkcai 

1. I think the major valid use case is to provide a default value of proper type, but I might be biased because of what I'm doing 🤷‍♂️😁 

2. That doesn't seem like a problem to me, because the user would need to be explicit about that. Maybe we can declare `default` and `optional` mutually exclusive in a same way as `default` and `required` are in https://github.com/hapijs/joi/issues/811 Anyway, I'm not very familiar with typescript generics at this scale (actually, I've just copied over return type of `required()` and everything seems to work) so I can't really imagine what `DefaultSchmea` would be.

**Comment by hjkcai** [comment]
Oops, seems that my assumption is correct. The demo code below outputs `'str'`. It means **Joi allows the type of the default value to be different with the type of the schema.**

```javascript
const Joi = require('joi')
const schema = Joi.number().default('str')
const result = Joi.attempt(undefined, schema)
console.log(result)    // 'str'
```

> so I can't really imagine what `DefaultSchmea` would be.

I admit that the code is messy and hard to read 🙁 I will do refactor at the same time.

You can imagine schema types as states of a state machine. And the value type is the state of the schema type (like a nested state machine). The state changes as you call schema methods:

```javascript
Joi.array()               // ArraySchema<never[]>
  .items(Joi.number())    // ArraySchema<number[]>
  .items(Joi.string())    // ArraySchema<(number | string)[]>
  .sparse(true)           // SparseArraySchema<(number | string)[]>
  .required()             // RequiredSparseArraySchema<(number | string)[]>
  .sparse(false)          // RequiredArraySchema<(number | string)[]>
```

Therefore, as the `default` method is implemented, new top level states must be added (e.g. `DefaultArraySchema`). Simply make `DefaultXXXSchema` impossible to change into `RequiredXXXSchema` so that calling `default()` on `required()` is disallowed (and vice versa).

**Comment by bard** [comment]
FWIW, I'd like to +1. Both on the subject and the gratitude for publishing `typesafe-joi`. :+1: 

I'm using `typesafe-joi` to populate a configuration object from environment variables; some values can have defaults, other must be provided by the user; if the latter aren't provided, the service must crash right away instead of moving on to application code. `Joi.attempt()` works great for this.

However, having the default values propagate as `string | undefined` and having to type-guard them in application code gives the impression that those values are allowed to be undefined at that stage, which is misleading.

@hjkcai's snippet helped.

**Comment by hjkcai** [comment]
@brabeji @bard @Agrimonia I have published typesafe-joi 2.0.0 alpha version, which solves this problem. Please have a try! If you found any bug, feel free to open another issue 😀

```
npm i typesafe-joi@next
```

**Comment by bard** [comment]
Setting a default value indeed now signals that the value cannot be undefined. That's great, thank you!

**Comment by brabeji** [comment]
Great news @hjkcai ! Looking forward to drop some `patch-package` patches in my project <3 thank you!
